### ISSUE TITLE
Add starter kits for WatsonX Tech Preview and for Conversational Search

### ISSUE THREAD

**Issue by rafael-nogueras** [watson-developer-cloud/assistant-toolkit#131]
# Tasks

- [ ] Create a new language model starter kit for the Watson Tech Preview using [its OpenAI spec](https://ibm.ent.box.com/folder/211349861203). This involves authoring a sample Action (similar to the existing one in the [OpenAI starter kit](https://github.com/watson-developer-cloud/assistant-toolkit/tree/master/integrations/extensions/starter-kits/language-model-openai)) and writing a corresponding `README.MD` file that explains how to configure it. The directory should be created in [the starter kit directory](https://github.com/watson-developer-cloud/assistant-toolkit/tree/master/integrations/extensions/starter-kits) and its name should be `language-model-watsonx-tech-preview`.
- [ ] Create a new use case starter kit for the Conversational Search use case using [its OpenAI spec and sample action](https://ibm.ent.box.com/folder/211349861203). This involves writing a corresponding `README.MD` file that explains how to configure it. The directory should be created in [the starter kit directory](https://github.com/watson-developer-cloud/assistant-toolkit/tree/master/integrations/extensions/starter-kits) and its name should be `language-model-conversational-search`.
- [ ] Add these and the other language model/use case starter kits to [the main index](https://github.com/watson-developer-cloud/assistant-toolkit/blob/master/integrations/extensions/README.md#jump-to).

**Comment by rafael-nogueras** [comment]
This issue was address in [this PR](https://github.com/watson-developer-cloud/assistant-toolkit/pull/132): closing.
